name: Publish Identity.Module.AuthManager on NuGet
 
on:
  push:
    branches: [ main ]
    paths: [ 'src/MinimalApi.Identity.AuthManager/**' ]
  workflow_dispatch:
      
env:
  NET_VERSION: '8.x'
  PROJECT_NAME: src/MinimalApi.Identity.AuthManager
  PROJECT_FILE: MinimalApi.Identity.AuthManager.csproj
  TAG_NAME: Identity.Module.AuthManager
  RELEASE_NAME: Identity.Module.AuthManager
  
jobs:
  build:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'

    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.4.2
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}

    - name: Package
      run: dotnet pack -c Release -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'

    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate
      
    - name: Publish on GitHub
      run: |
        dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push **\*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      
    # - name: Create release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #       tag_name: ${{ env.TAG_NAME }}_v${{ steps.nbgv.outputs.NuGetPackageVersion }}
    #       release_name: ${{ env.RELEASE_NAME }} ${{ steps.nbgv.outputs.NuGetPackageVersion }}
    #       body: Integration package, requires the Identity.Module.API package to work.
    #       draft: false
    #       prerelease: false
